"""
Django settings for morfee_frontier project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!*1&dt41#1+q6em$&gs_z=)ouctiu(-g9cbq%&16%mbm4p=z@g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', '10.244.8.31', 'https://monkfish-app-ir8tl.ondigitalocean.app', 'monkfish-app-ir8tl.ondigitalocean.app', 'www.morfee.com.co', 'morfee.com.co']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'channels',
    'morfee_frontier',
    'users',
    'aseguramiento',
    'reservas',
    'vacunacion',
    'auditorias',
    'financiero',
    'servicios',
    'ghg',
    'mf_consulta',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'morfee_frontier.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'morfee_frontier.wsgi.application'

# ASGI_APPLICATION = 'morfee_frontier.asgi.'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_morfee',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db_morfee',
        'USER': 'doadmin',
        'PASSWORD': 'zcnkr6zdz2depana',
        'HOST': 'db-mysql-nyc3-80737-do-user-7990340-0.b.db.ondigitalocean.com',
        'PORT': '25060',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

# CUSTOM_URI_MONGO = 'mongodb+srv://carvi:ac2502412@sgsss.yv4ar.gcp.mongodb.net/morfeeweb?authSource=admin'
CUSTOM_URI_MONGO = 'mongodb+srv://djcarvi:Ac2502412@sgsss.yv4ar.gcp.mongodb.net/morfeeweb?authSource=admin'
CUSTOM_DB_MONGO = 'morfeeweb'

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

AUTH_USER_MODEL = 'users.UserMorfee'


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# LOCAL CONFIG
# STATIC_URL = '/static/'
# STATICFILES_DIRS = ["C:/Almacen/static",]
# MEDIA_ROOT = "C:/Almacen/media"

# SERVER CONFIG
AWS_ACCESS_KEY_ID = 'VDPJXJOCWLN4YLB7WLVG'
AWS_SECRET_ACCESS_KEY = 'oCXyf0QEppqysauxt3mdRV03G4Cs3OSrkQLnPZeMuZk'
AWS_STORAGE_BUCKET_NAME = 'almacenmorfee'
AWS_S3_ENDPOINT_URL = 'https://almacenmorfee.nyc3.digitaloceanspaces.com'
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
AWS_QUERYSTRING_AUTH = False
AWS_LOCATION = 'almacenamiento'

STATIC_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_LOCATION}/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"]

STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
